controller_list:
  - name: fake_RB5_controller
    joints:
      - base
      - shoulder
      - elbow
      - wrist1
      - wrist2
      - wrist3
initial:  # Define initial robot poses.
  - group: RB5
    pose: Home